[workspace]
members = [
  ".",
  "tern-core",
  "tern-cli",
  "tern-derive",
  "examples/*",
]
default-members = ["tern-core", "tern-cli", "tern-derive"]
exclude = []

[workspace.package]
version = "3.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/quasi-coherent/tern"
keywords = ["embedded", "database", "migrations", "postgres", "mysql"]
categories = ["database"]
authors = ["Daniel Donohue <daniel.donohue@beyondidentity.com>"]
rust-version = "1.81.0"

[package]
name = "tern"
readme = "README.md"
description = "Embedded database migrations in SQL or Rust."
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
cli = ["tern-cli"]

sqlx_postgres = ["tern-core/sqlx_postgres"]
sqlx_mysql = ["tern-core/sqlx_mysql"]
sqlx_sqlite = ["tern-core/sqlx_sqlite"]

[workspace.dependencies]
tern-core = { version = "=3.0.0", path = "tern-core" }
tern-cli = { version = "=3.0.0", path = "tern-cli" }
tern-derive = { version = "=3.0.0", path = "tern-derive" }

[dependencies]
tern-core.workspace = true
tern-cli = { workspace = true, optional = true }
tern-derive.workspace = true

[dev-dependencies]
tokio = { version = "1.45", default-features = false, features = ["rt", "macros"] }
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio"] }

[[test]]
name = "postgres"
path = "tests/postgres/postgres.rs"
required-features = ["sqlx_postgres"]