services:
  postgres:
    build:
      dockerfile: postgres16.Dockerfile
      context: "etc"
    environment:
      POSTGRES_USER: "tern"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "tern"
    ports:
      - "5433:5432"
