services:

  postgres:
    build:
      dockerfile: postgres16.Dockerfile
      context: "etc"
    environment:
      POSTGRES_USER: "tern"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "tern"
    ports:
      - "5433:5432"

  mysql:
    image:
      mysql:8.0-bookworm
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "tern"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "tern"
    ports:
      - "3307:3306"
