use futures_core::future::Future;
use std::borrow::Cow;
use std::fmt::{self, Display, Formatter};
use tern_core::error::{ErrorKind, MigrationError, TernResult};
use tern_test::property::DynProperty;
use tern_test::report::{StepReport, TestReport};
use tern_test::{TestDb, TestExecutor};

use crate::app::{Tern, TernApp};
use crate::ops::migrate::{ApplyArgs, RevertArgs};
use crate::ops::{OpError, OpResult};

/// An error during testing.
#[derive(Debug, thiserror::Error)]
pub struct TestError {
    version: i64,
    reason: Cow<'static, str>,
}

impl TestError {
    /// Create a new test error.
    pub fn new<T: Into<Cow<'static, str>>>(version: i64, msg: T) -> Self {
        Self { version, reason: msg.into() }
    }
}

impl Display for TestError {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(
            f,
            r#"{{"version": {}, "reason": "{}"}}"#,
            self.version, &self.reason
        )
    }
}

impl MigrationError for TestError {
    fn message(&self) -> String {
        self.reason.to_string()
    }

    fn kind(&self) -> ErrorKind {
        ErrorKind::Validation
    }
}

/// A test generated by `tern::test_suite!`.
#[derive(Clone, Copy, Debug)]
pub enum TestCase {
    /// Apply every migration in order.
    ApplyAll,
    /// Exercise the up/down pair at this version.
    UpDown {
        /// The version of the pair.
        version: i64,
    },
}

/// The testing interface of a `TernApp`.
pub struct TernTest<T> {
    app: Tern<T>,
    testdb: TestDb,
    report: TestReport,
}

impl<T> TernTest<T>
where
    T: TernApp,
    T::Exec: TestExecutor,
{
    pub(super) async fn new<F, Fut>(
        name: &str,
        base_url: &str,
        keep: bool,
        mut f: F,
    ) -> TernResult<Self>
    where
        F: FnMut(T::Exec) -> Fut,
        Fut: Future<Output = TernResult<T>>,
    {
        // Use the base connection string to construct a short-lived executor
        // that creates the test database.  It's dropped when this function has
        // returned a value.
        let testdb = TestDb::new(base_url)?;
        let testdb_name = testdb.testdb_name();

        let mut base_exec = testdb.new_base_executor::<T::Exec>().await?;
        base_exec.create_database(&testdb).await?;

        // Now connect with the new database to create the test executor.
        let exec = testdb.new_test_executor::<T::Exec>().await?;
        let t = f(exec).await?;
        let app = Tern::new(t);

        let report = TestReport::new(name, testdb_name, base_url, keep);

        Ok(Self { app, testdb, report })
    }

    pub(super) fn into_parts(self) -> (Tern<T>, TestDb, TestReport) {
        (self.app, self.testdb, self.report)
    }

    /// Get a mutable reference to the `Tern` app for arbitrary assertions.
    pub fn get_app_mut(&mut self) -> &mut Tern<T> {
        &mut self.app
    }

    /// Apply every migration in order, verifying that the history table matches
    /// the local source.
    pub async fn apply_all(&mut self) -> TernResult<()> {
        let (label, slast) = match self.app.up_migrations().range() {
            Some((_, v)) => (format!("apply all V1..V{v}"), v),
            _ => ("apply all (empty)".into(), 0),
        };

        self.report
            .step(label, async {
                do_op(self.app.apply(ApplyArgs::new().all()).await)?;
                // Check the latest that got saved in the DB.  It should be
                // equal to the `slast` value above.
                let alast =
                    self.app.latest_applied().await?.map(|m| m.version());

                if alast.is_none_or(|v| v < slast) {
                    return Err(TestError::new(
                        alast.unwrap_or_default(),
                        format!("expected apply through {slast}"),
                    ))?;
                }
                Ok(())
            })
            .await
    }

    /// Check the up/down migration at the given version against the given
    /// property.
    ///
    /// The choreography goes:
    /// 0. Apply through `version -1`.
    /// 1. Check the `before` assertion of the property.
    /// 2. Apply the up migration.
    /// 3. Check the `after` assertion of the property.
    /// 3. Check the `should_revert` condition.
    /// 4. If `true`, apply the down migration.
    /// 5. Check the `before` assertion again.
    pub async fn check_property(
        &mut self,
        version: i64,
        prop: &dyn DynProperty<T>,
    ) -> TernResult<()> {
        self.apply_below(version).await?;
        self.report
            .step(
                format!("assert before V{version} init"),
                prop.before(&mut self.app),
            )
            .await?;
        self.report
            .step(format!("apply up V{version}"), async {
                do_op(self.app.apply(ApplyArgs::new().to(version)).await)
            })
            .await?;
        self.report
            .step(format!("assert after V{version}"), prop.after(&mut self.app))
            .await?;
        // Should the down migration run in this case?
        if !prop.should_revert(&mut self.app).await? {
            return Ok(());
        }
        self.report
            .step(format!("apply down V{version}"), async {
                do_op(self.app.revert(RevertArgs::new(version)).await)
            })
            .await?;
        self.report
            .step(
                format!("assert before V{version} final"),
                prop.before(&mut self.app),
            )
            .await
    }

    /// A structural test for up/down pairs only asserts that both can run in
    /// order.
    pub async fn check_structural(&mut self, version: i64) -> TernResult<()> {
        self.apply_below(version).await?;
        self.report
            .step(format!("apply up V{version}"), async {
                do_op(self.app.apply(ApplyArgs::new().to(version)).await)
            })
            .await?;
        self.report
            .step(format!("apply down V{version}"), async {
                do_op(self.app.revert(RevertArgs::new(version)).await)
            })
            .await?;
        self.report.push(StepReport::unverified(format!(
            "V{version} ran with no property test"
        )));
        Ok(())
    }

    /// Apply all migrations up to, but not including, `version`.
    pub async fn apply_below(&mut self, version: i64) -> TernResult<()> {
        let target = version - 1;
        if target <= 0 {
            return Ok(());
        }
        self.report
            .step(format!("apply V1..V{target}"), async {
                do_op(self.app.apply(ApplyArgs::new().to(target)).await)
            })
            .await
    }
}

/// Configuring a test.
///
/// Typically built behind-the-macros.
#[derive(Clone)]
pub struct TestConfig {
    name: String,
    url: Option<String>,
    keep_db: bool,
}

impl TestConfig {
    /// New from test name and optional environment variable holding the base
    /// DB URL.
    pub fn new(name: &str, key: Option<&str>) -> Self {
        let key = key.unwrap_or("TERN_TEST_DB_URL");
        let url = std::env::var(key).ok();
        Self { name: name.to_string(), url, keep_db: false }
    }

    /// Keep the DB after the test.
    pub fn keep_db(mut self) -> Self {
        self.keep_db = true;
        self
    }

    pub(super) fn should_keep_db(&self) -> bool {
        self.keep_db
    }

    pub(super) fn get_name(&self) -> &str {
        &self.name
    }

    pub(super) fn get_url(&self) -> Option<&str> {
        self.url.as_deref()
    }
}

fn do_op(res: OpResult) -> TernResult<()> {
    res.map(drop).map_err(OpError::into_inner)
}
