[package]
name = "tern-core"
description = "Core interfaces and types for `tern` migration tooling."
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

sqlx_postgres = ["sqlx", "sqlx/postgres"]
sqlx_mysql = ["sqlx", "sqlx/mysql"]
sqlx_sqlite = ["sqlx", "sqlx/sqlite"]

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
display_json = "0.2.1"
futures-core = "0.3.31"
log = "0.4.27"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = {version = "0.8.5", features = ["chrono"], optional = true }
thiserror = "2.0.12"
